//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreOfAutoparts.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manufacturer
    {
        public int ID { get; set; }
        public string NameOfManufacturer { get; set; }
        public int CountryID { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
